#FROM : É de qual imagem que eu quero partir
FROM ubuntu:18.04    
#RUN : Quando eu preciso instalar alguma coisa no meu container eu uso o RUN     
RUN  apt-get update && apt-get install -y nginx && rm -rf /var/lib/apt/lists/*
#EXPOSE : É a porta que eu quero expor"  
EXPOSE 80 

#COPY : É para copiar arquivos do host para o container
COPY index.html /var/www/html/index.html
#CMD : É o comando que eu quero executar na execução do container
CMD ["nginx", "-g", "daemon off;"] 
#WORKDIR : É para definir o diretório de trabalho
WORKDIR /var/www/html 
#ENV : É para definir variáveis de ambiente
ENV APP_VERSION=1.0.0
#ENTRYPOINT : É para definir o comando que vai ser executado na execução do container
ENTRYPOINT ["nginx", "-g", "daemon off;"]