FROM golang:1.18 as buildando
WORKDIR /app
COPY . ./
RUN go mod init hello
RUN go build -o /app/hello


#SHELL: É para definir o shell que vai ser usado no container
SHELL ["/bin/sh", "-c"]
FROM alpine:3.15.9
COPY --from=buildando /app/hello /app/hello
ENV app=hello-world
#Volume: É para definir um volume no container
VOLUME ["/app"]
CMD ["/app/hello"]